services:
  
  web:
    build:
      context: ./web
      target: dev
    volumes:
      - ./web:/app
    ports:
      - "45678:5678"
    networks:
      - app_net_12345
    env_file:
      - ./web/apps/web-antd/.env.local


networks:
  app_net_12345:
    driver: bridge 