"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# crypto 对称加密
# key 44 位 base64 字符
AES_KEY = os.getenv('AES_KEY')
AES_SALT = os.getenv('AES_SALT')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 演示环境配置
DEMO_MODE = os.getenv('DEMO_MODE', 'False').lower() in ('true', '1')

ALLOWED_HOSTS = [
    '*',
]
INTERNAL_IPS = [
    '*',
]

CORS_ORIGIN_ALLOW_ALL = True  # 允许跨域名访问
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS =True

# Application definition

INSTALLED_APPS = [
    "simpleui",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'django_filters',
    'corsheaders',
    'rest_framework.authtoken',
    # 'channels',
    "system",
    "ai",
    "work_order",
    "external_platform",
    "gateway",  # 平台网关SDK
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 演示环境中间件 - 全局禁止修改和删除操作
if DEMO_MODE:
    MIDDLEWARE.append('utils.middleware.DemoModeMiddleware')

AUTH_USER_MODEL = 'system.User'
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'django_vue'),
        'USER': os.getenv('DB_USER', 'chenze'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'my-secret-pw'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# 设置为中国标准时间（CST，东八区）
TIME_ZONE = 'Asia/Shanghai'

# 启用国际化（多语言）
USE_I18N = True

# 启用本地化（格式化日期、数字等）
USE_L10N = True

# 是否使用时区支持（建议开启）
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  #自己在根目录下创建media文件夹
# Default primary key field type
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.CustomPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.OrderingFilter',
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'utils.authentication.BearerTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# ================= Redis 缓存配置 =================
# 构建 Redis URL，支持有密码和无密码的情况
def build_redis_url(db=0):
    redis_host = os.environ.get('REDIS_HOST', 'localhost')
    redis_port = os.environ.get('REDIS_PORT', 6379)
    redis_password = os.environ.get('REDIS_PASSWORD', '')
    
    if redis_password:
        return f"redis://:{redis_password}@{redis_host}:{redis_port}/{db}"
    else:
        return f"redis://{redis_host}:{redis_port}/{db}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": build_redis_url(1),  # 使用数据库1作为缓存
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# SESSION 存 Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# ================= Celery 配置（适配环境变量） =================
CELERY_BROKER_URL = build_redis_url(0)  # 使用数据库0作为消息队列
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
# 时区设置
CELERY_TIMEZONE = 'Asia/Shanghai'
# 任务序列化方式
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# ================= Celery任务路由配置 =================
CELERY_TASK_ROUTES = {
    # 网关SDK任务路由
    'gateway.tasks.keepalive_task': {
        'queue': 'gateway',
        'routing_key': 'gateway.keepalive'
    },
    'gateway.tasks.session_health_check_task': {
        'queue': 'gateway',
        'routing_key': 'gateway.health'
    },
    'gateway.tasks.session_cleanup_task': {
        'queue': 'gateway',
        'routing_key': 'gateway.cleanup'
    },
    'gateway.tasks.test_connectivity_task': {
        'queue': 'gateway',
        'routing_key': 'gateway.connectivity'
    }
}

# ================= Celery任务配置注解 =================
CELERY_TASK_ANNOTATIONS = {
    # 网关保活任务
    'gateway.tasks.keepalive_task': {
        'rate_limit': '6/m',  # 每分钟最多6次
        'time_limit': 120,    # 2分钟超时
        'soft_time_limit': 90, # 90秒软超时
        'retry_backoff': True,
        'retry_backoff_max': 300,  # 最大重试间隔5分钟
        'retry_jitter': True
    },
    # 网关健康检查任务
    'gateway.tasks.session_health_check_task': {
        'rate_limit': '10/m',
        'time_limit': 60,
        'soft_time_limit': 45,
        'retry_backoff': True
    },
    # 网关会话清理任务
    'gateway.tasks.session_cleanup_task': {
        'rate_limit': '2/h',   # 每小时最多2次
        'time_limit': 300,     # 5分钟超时
        'soft_time_limit': 240
    },
    # 网关连通性测试任务
    'gateway.tasks.test_connectivity_task': {
        'rate_limit': '4/m',
        'time_limit': 30,
        'soft_time_limit': 20
    }
}

CELERY_BEAT_SCHEDULE = {
    'batch_fetch_workorders': {
        'task': 'external_platform.tasks.batch_fetch_workorders_task.batch_fetch_workorders_task',
        'schedule': 300,  # 每 5 分钟执行一次
        'options': {
            'expires': 1800,  # 任务过期时间30分钟
        }
    },
    # ================= 网关SDK任务 =================
    # 网关保活任务
    'gateway-keepalive': {
        'task': 'gateway.tasks.keepalive_task',
        'schedule': int(os.getenv('GATEWAY_KEEPALIVE_INTERVAL', '300')),
        'options': {
            'queue': 'gateway',
            'routing_key': 'gateway.keepalive',
            'priority': 8,
            'expires': 120
        }
    },
    # 网关健康检查任务
    'gateway-health-check': {
        'task': 'gateway.tasks.session_health_check_task',
        'schedule': int(os.getenv('GATEWAY_HEALTH_CHECK_INTERVAL', '600')),
        'options': {
            'queue': 'gateway',
            'routing_key': 'gateway.health',
            'priority': 6,
            'expires': 300
        }
    },
    # 网关会话清理任务
    'gateway-session-cleanup': {
        'task': 'gateway.tasks.session_cleanup_task',
        'schedule': int(os.getenv('GATEWAY_CLEANUP_INTERVAL', '3600')),
        'options': {
            'queue': 'gateway',
            'routing_key': 'gateway.cleanup',
            'priority': 3,
            'expires': 1800
        }
    },
    # 网关连通性测试任务
    'gateway-connectivity-test': {
        'task': 'gateway.tasks.test_connectivity_task',
        'schedule': int(os.getenv('GATEWAY_CONNECTIVITY_TEST_INTERVAL', '1800')),
        'options': {
            'queue': 'gateway',
            'routing_key': 'gateway.connectivity',
            'priority': 4,
            'expires': 900
        }
    }
}
# celery 配置结束

# ================= 外部平台配置 =================
# 超级鹰验证码配置
CHAOJIYING_CONFIG = {
    'username': os.getenv('CHAOJIYING_USERNAME', ''),
    'password': os.getenv('CHAOJIYING_PASSWORD', ''),
    'software_id': os.getenv('CHAOJIYING_SOFTWARE_ID', ''),
    'timeout': 30
}

# ================= 平台网关SDK配置 =================
GATEWAY_SETTINGS = {
    'username': os.getenv('GATEWAY_USERNAME', ''),
    'password': os.getenv('GATEWAY_PASSWORD', ''),
    'base_url': os.getenv('GATEWAY_BASE_URL', ''),
    'captcha_base_url': os.getenv('GATEWAY_CAPTCHA_BASE_URL', ''),
    'login_url': os.getenv('GATEWAY_LOGIN_URL', '/login'),
    'request_timeout': int(os.getenv('GATEWAY_REQUEST_TIMEOUT', '30')),
    'session_timeout': int(os.getenv('GATEWAY_SESSION_TIMEOUT', '3600')),
    'max_retries': int(os.getenv('GATEWAY_MAX_RETRIES', '3')),
    'redis_key_prefix': os.getenv('GATEWAY_REDIS_KEY_PREFIX', 'gateway:'),
    'user_agent': os.getenv('GATEWAY_USER_AGENT', 
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'),
    
    # 验证码相关配置
    'captcha_type': int(os.getenv('GATEWAY_CAPTCHA_TYPE', '1004')),
    'captcha_max_retries': int(os.getenv('GATEWAY_CAPTCHA_MAX_RETRIES', '3')),
    
    # Celery任务调度配置
    'keepalive_interval': int(os.getenv('GATEWAY_KEEPALIVE_INTERVAL', '300')),  # 5分钟
    'health_check_interval': int(os.getenv('GATEWAY_HEALTH_CHECK_INTERVAL', '600')),  # 10分钟
    'cleanup_interval': int(os.getenv('GATEWAY_CLEANUP_INTERVAL', '3600')),  # 1小时
    'connectivity_test_interval': int(os.getenv('GATEWAY_CONNECTIVITY_TEST_INTERVAL', '1800')),  # 30分钟
    
    # 任务开关
    'enable_keepalive_task': os.getenv('GATEWAY_ENABLE_KEEPALIVE_TASK', 'True').lower() in ('true', '1'),
    'enable_health_check_task': os.getenv('GATEWAY_ENABLE_HEALTH_CHECK_TASK', 'True').lower() in ('true', '1'),
    'enable_cleanup_task': os.getenv('GATEWAY_ENABLE_CLEANUP_TASK', 'True').lower() in ('true', '1'),
    'enable_connectivity_test_task': os.getenv('GATEWAY_ENABLE_CONNECTIVITY_TEST_TASK', 'True').lower() in ('true', '1'),
}

# 外部平台配置现在从数据库读取，无需静态配置

# 外部平台任务配置
EXTERNAL_PLATFORM_TASK_CONFIG = {
    'batch_fetch_workorders_task': {
        'page_size': 50,
        'max_pages': 10,
        'retry_delay': 300,
        'timeout': 30,
    },
    'fetch_single_workorder_task': {
        'retry_delay': 60,
        'timeout': 30,
    },
    'sync_data_2_base_order': {
        'retry_delay': 30,
    },
    'sync_edit_order': {
        'max_retries': 3,
        'retry_delay': 60,  # 重试延迟(秒)
        'timeout': 300  # 任务超时时间(秒)
    }
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'ignore_auth_user': {
            '()': 'utils.filters_logs.IgnoreSQLFilter',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['ignore_auth_user'],
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',   # 只在 DEBUG 模式时生效
        },
    }
}

ASGI_APPLICATION = 'backend.asgi.application'


# 简单用内存通道层
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }

if os.path.exists(os.path.join(BASE_DIR, 'backend/local_settings.py')):
    from backend.local_settings import *