# Generated by Django 5.2.1 on 2025-09-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('name', models.CharField(db_comment='名称', max_length=100)),
                ('sign', models.CharField(db_comment='标识', max_length=50, unique=True)),
                ('base_url', models.URLField(db_comment='基础URL')),
                ('captcha_type', models.IntegerField(db_comment='验证码类型', default=1004, help_text='超级鹰验证码类型')),
                ('session_timeout_hours', models.IntegerField(db_comment='会话超时时间(小时)', default=24)),
                ('retry_limit', models.IntegerField(db_comment='重试次数限制', default=3)),
                ('is_active', models.BooleanField(db_comment='是否启用', default=True)),
                ('description', models.TextField(blank=True, db_comment='平台描述', null=True)),
            ],
            options={
                'verbose_name': '外部平台',
                'verbose_name_plural': '外部平台',
                'db_table': 'external_platform',
                'unique_together': {('sign',)},
            },
        ),
        migrations.CreateModel(
            name='PlatformEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('endpoint_type', models.CharField(choices=[('captcha', '验证码'), ('login', '登录'), ('check_status', '状态检查'), ('workorder_list', '工单列表'), ('logout', '登出'), ('custom', '自定义')], max_length=50, verbose_name='端点类型')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='端点名称')),
                ('path', models.CharField(max_length=200, verbose_name='路径')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='请求方式')),
                ('require_auth', models.BooleanField(default=False, verbose_name='是否需要鉴权')),
                ('description', models.TextField(blank=True, null=True, verbose_name='端点说明')),
                ('platform', models.ForeignKey(db_column='external_platform_id', on_delete=django.db.models.deletion.CASCADE, to='external_platform.platform', verbose_name='外部平台')),
            ],
            options={
                'verbose_name': '平台端点配置',
                'verbose_name_plural': '平台端点配置',
                'db_table': 'external_platform_endpoint',
                'unique_together': {('platform', 'endpoint_type')},
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('endpoint_path', models.CharField(max_length=255, verbose_name='端点路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='方法')),
                ('payload', models.JSONField(null=True, verbose_name='请求参数')),
                ('status_code', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='响应耗时')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='响应体')),
                ('hook', models.JSONField(blank=True, null=True, verbose_name='请求后钩子')),
                ('hook_result', models.JSONField(blank=True, null=True, verbose_name='钩子结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='请求错误消息')),
                ('tag', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('platform', models.ForeignKey(db_column='external_platform_id', db_comment='关联外部平台', on_delete=django.db.models.deletion.CASCADE, to='external_platform.platform', verbose_name='外部平台')),
                ('platform_endpoint', models.ForeignKey(blank=True, db_column='external_platform_endpoint_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='external_platform.platformendpoint', verbose_name='平台端点')),
            ],
            options={
                'verbose_name': '外部系统请求日志',
                'verbose_name_plural': '外部系统请求日志',
                'db_table': 'external_request_log',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAuthCaptchaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('request_log', models.ForeignKey(db_column='external_request_log_id', on_delete=django.db.models.deletion.CASCADE, to='external_platform.requestlog', verbose_name='请求记录')),
            ],
            options={
                'verbose_name': '外部系统验证码识别结果日志',
                'verbose_name_plural': '外部系统验证码识别结果日志',
                'db_table': 'external_auth_captcha_log',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('auth', models.JSONField(blank=True, null=True, verbose_name='鉴权信息')),
                ('status', models.CharField(choices=[('active', '活跃'), ('expired', '过期'), ('failed', '失败')], default='expired', max_length=50, verbose_name='鉴权状态')),
                ('expire_time', models.DateTimeField(blank=True, help_text='过期时间', null=True, verbose_name='过期时间')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='登录时间')),
                ('platform', models.ForeignKey(db_column='external_platform_id', db_comment='关联外部平台', on_delete=django.db.models.deletion.CASCADE, to='external_platform.platform', verbose_name='外部平台')),
            ],
            options={
                'verbose_name': '外部系统鉴权会话',
                'verbose_name_plural': '外部系统鉴权会话',
                'db_table': 'external_auth_session',
                'ordering': ['update_time'],
                'unique_together': {('platform', 'account')},
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('config_key', models.CharField(max_length=100, verbose_name='配置键')),
                ('config_value', models.JSONField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置说明')),
                ('platform', models.ForeignKey(db_column='external_platform_id', on_delete=django.db.models.deletion.CASCADE, to='external_platform.platform', verbose_name='外部平台')),
            ],
            options={
                'verbose_name': '平台配置',
                'verbose_name_plural': '平台配置',
                'db_table': 'external_platform_config',
                'unique_together': {('platform', 'config_key')},
            },
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['platform', 'create_time'], name='external_re_externa_4d4bce_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['endpoint_path', 'status_code'], name='external_re_endpoin_a9e5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['account', 'create_time'], name='external_re_account_37103f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalauthcaptchalog',
            index=models.Index(fields=['request_log'], name='request_log_id_idx'),
        ),
    ]
