# Generated by Django 5.2.1 on 2025-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='login_config',
            field=models.TextField(blank=True, db_comment='登录配置(json 加密)', null=True, verbose_name='登录配置'),
        ),
    ]
