# Generated by Django 5.2.1 on 2025-09-07 16:57

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0002_platform_login_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='login_config',
            field=common.fields.EncryptedTextField(blank=True, db_comment='登录配置(json 加密)', null=True, verbose_name='登录配置'),
        ),
    ]
