# Generated by Django 5.2.1 on 2025-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0003_alter_platform_login_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformendpoint',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='载荷'),
        ),
    ]
