# Generated by Django 5.2.1 on 2025-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0004_platformendpoint_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('captcha', '验证码'), ('login', '登录'), ('check_status', '状态检查'), ('workorder_list', '工单列表'), ('workorder_detail', '工单详情'), ('workorder_related_record', '工单关联'), ('workorder_work_unit_record', '工单办理单位'), ('workorder_poerate_record', '工单办理单位'), ('workorder_attachment_record', '工单附件'), ('workorder_flow_record', '工单流程'), ('workorder_action_edit', '编辑工单'), ('workorder_action_disposal', '处置工单'), ('workorder_action_send', '下派工单'), ('workorder_action_back', '退回工单'), ('workorder_action_postpone', '延期工单'), ('workorder_action_supervise', '督办工单'), ('logout', '登出'), ('custom', '自定义')], max_length=50, verbose_name='端点类型'),
        ),
    ]
