# Generated by Django 5.2.1 on 2025-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0005_alter_platformendpoint_endpoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformendpoint',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='载荷'),
        ),
    ]
