# Generated by Django 5.2.1 on 2025-09-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0006_alter_platformendpoint_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDistrictNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('name', models.CharField(db_comment='名称', max_length=100, verbose_name='名称')),
                ('code', models.CharField(db_comment='编码', max_length=10, unique=True, verbose_name='编码')),
                ('parent', models.ForeignKey(db_comment='父节点', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='external_platform.externaldistrictnode', to_field='code', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '区县节点',
                'verbose_name_plural': '区县节点',
                'db_table': 'external_district_node',
                'ordering': ['-update_time'],
                'indexes': [models.Index(fields=['code'], name='code_idx')],
            },
        ),
    ]
