# Generated by Django 5.2.1 on 2025-09-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_platform', '0007_externaldistrictnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldistrictnode',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='external_platform.externaldistrictnode', to_field='code', verbose_name='父节点'),
        ),
    ]
