# Generated by Django 5.2.1 on 2025-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_post_alter_dept_creator_alter_dept_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictdata",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="dicttype",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, verbose_name="角色状态"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "启用")], default=1, verbose_name="状态"
            ),
        ),
    ]
