# Generated by Django 5.2.1 on 2025-08-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_dept_creator_alter_dept_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="location",
            field=models.CharField(
                blank=True, db_comment="<IP> 地理位置", default="", max_length=200
            ),
        ),
    ]
