# Generated by Django 5.2.1 on 2025-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_alter_dictdata_status_alter_dicttype_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatarUrl",
            new_name="avatar_url",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(
                blank=True,
                db_constraint=False,
                related_name="users",
                to="system.role",
                verbose_name="角色",
            ),
        ),
    ]
