# Generated by Django 5.2.1 on 2025-07-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_rename_avatarurl_user_avatar_url_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="login_date",
        ),
        migrations.AddField(
            model_name="menu",
            name="sort",
            field=models.IntegerField(
                default=0, help_text="数值越小越靠前", verbose_name="显示排序"
            ),
        ),
    ]
