# Generated by Django 5.2.1 on 2025-07-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_remove_user_login_date_menu_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumeta",
            name="hide_children_in_menu",
            field=models.BooleanField(db_comment="隐藏子菜单", default=False),
        ),
        migrations.AddField(
            model_name="menumeta",
            name="hide_in_menu",
            field=models.BooleanField(db_comment="隐藏菜单", default=False),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="affix_tab",
            field=models.BooleanField(db_comment="固定标签页", default=False),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="badge",
            field=models.CharField(blank=True, db_comment="徽章文本", max_length=50),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="badge_type",
            field=models.CharField(blank=True, db_comment="徽章类型", max_length=20),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="badge_variants",
            field=models.CharField(blank=True, db_comment="徽章样式", max_length=20),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="icon",
            field=models.CharField(blank=True, db_comment="图标", max_length=100),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="iframe_src",
            field=models.URLField(blank=True, db_comment="内嵌页面URL"),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="link",
            field=models.URLField(blank=True, db_comment="外部链接"),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="order",
            field=models.IntegerField(db_comment="排序", default=0),
        ),
        migrations.AlterField(
            model_name="menumeta",
            name="title",
            field=models.CharField(db_comment="标题", max_length=200),
        ),
    ]
