# Generated by Django 5.2.1 on 2025-07-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "system",
            "0006_menumeta_hide_children_in_menu_menumeta_hide_in_menu_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["meta__sort", "id"],
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单管理",
            },
        ),
        migrations.RenameField(
            model_name="menumeta",
            old_name="order",
            new_name="sort",
        ),
    ]
