# Generated by Django 5.2.1 on 2025-07-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_alter_menu_options_rename_order_menumeta_sort"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_comment="是否软删除", default=False),
                ),
                (
                    "username",
                    models.CharField(db_comment="用户账号", default="", max_length=50),
                ),
                (
                    "result",
                    models.IntegerField(
                        choices=[(0, "失败"), (1, "成功")],
                        db_comment="登录结果",
                        default=1,
                    ),
                ),
                ("user_ip", models.CharField(db_comment="用户 IP", max_length=50)),
                (
                    "user_agent",
                    models.CharField(db_comment="浏览器 UA", max_length=512),
                ),
            ],
            options={
                "verbose_name": "系统访问记录",
                "verbose_name_plural": "系统访问记录",
                "db_table": "system_login_log",
                "ordering": ["-id"],
            },
        ),
    ]
