# Generated by Django 5.2.1 on 2025-07-10 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_comment="是否软删除", default=False),
                ),
                ("name", models.CharField(db_comment="名称", max_length=255)),
                ("platform", models.CharField(db_comment="平台", max_length=255)),
                ("api_key", models.CharField(db_comment="密钥", max_length=255)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        db_comment="自定义 API 地址",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        db_comment="状态",
                        default=0,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI API 密钥",
                "verbose_name_plural": "AI API 密钥",
                "db_table": "ai_api_key",
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_comment="是否软删除", default=False),
                ),
                ("name", models.CharField(db_comment="模型名字", max_length=64)),
                ("sort", models.IntegerField(db_comment="排序", default=0)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        db_comment="状态",
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                ("platform", models.CharField(db_comment="模型平台", max_length=32)),
                ("model", models.CharField(db_comment="模型标识", max_length=64)),
                (
                    "temperature",
                    models.FloatField(blank=True, db_comment="温度参数", null=True),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True, db_comment="单条回复的最大 Token 数量", null=True
                    ),
                ),
                (
                    "max_contexts",
                    models.IntegerField(
                        blank=True, db_comment="上下文的最大 Message 数量", null=True
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        db_comment="API 秘钥编号",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai.aiapikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 模型",
                "verbose_name_plural": "AI 模型",
                "db_table": "ai_model",
            },
        ),
    ]
