# Generated by Django 5.2.1 on 2025-07-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_alter_chatrole_knowledge_alter_chatrole_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(
                blank=True,
                db_comment="模型类型",
                max_length=32,
                null=True,
                verbose_name="模型类型",
            ),
        ),
    ]
