# Generated by Django 5.2.1 on 2025-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_alter_aiapikey_api_key_alter_aiapikey_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="工具名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="工具描述"
                    ),
                ),
                ("status", models.SmallIntegerField(verbose_name="状态")),
            ],
            options={
                "verbose_name": "AI 工具",
                "verbose_name_plural": "AI 工具",
                "db_table": "ai_tool",
            },
        ),
        migrations.AlterModelOptions(
            name="aimodel",
            options={"verbose_name": "模型配置", "verbose_name_plural": "模型配置"},
        ),
    ]
