# Generated by Django 5.2.1 on 2025-07-21 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Drawing",
        ),
        migrations.AlterModelTable(
            name="drawing",
            table="ai_drawing",
        ),
    ]
