# Generated by Django 5.2.1 on 2025-08-12 17:38

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('title', models.CharField(db_comment='标题', max_length=100)),
                ('mobile', models.CharField(db_comment='手机号', max_length=15, validators=[utils.utils.validate_mobile])),
                ('sort', models.IntegerField(db_comment='排序', default=0)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '示例',
                'verbose_name_plural': '示例',
                'db_table': 'work_order_demo',
                'ordering': ['sort'],
            },
        ),
    ]
