# Generated by Django 5.2.1 on 2025-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='external_id',
            field=models.BigIntegerField(db_comment='工单ID', default=0, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='base',
            name='sync_task_id',
            field=models.CharField(db_comment='同步任务ID', max_length=36, verbose_name='同步任务ID'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='pull_task_id',
            field=models.CharField(db_comment='拉取任务ID', max_length=36, verbose_name='拉取任务ID'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='raw_data',
            field=models.JSONField(db_comment='原始工单数据', default=dict, verbose_name='工单信息'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='sync_task_id',
            field=models.CharField(db_comment='同步任务ID', max_length=36, verbose_name='同步任务ID'),
        ),
    ]
