# Generated by Django 5.2.1 on 2025-09-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_meta_external_id_alter_base_sync_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='external_handle_rel_expire_time',
            field=models.CharField(blank=True, db_comment='处置实际到期时间', max_length=50, null=True, verbose_name='处置实际到期时间'),
        ),
    ]
