# Generated by Django 5.2.1 on 2025-08-25 01:43

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_base_externalapilog_externalauthcaptchalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('api_endpoint', models.JSONField(blank=True, db_comment='API_ENDPOINT', default={'method': 'POST', 'url': '/payroll3/sub_act.php'}, null=True, verbose_name='API_ENDPOINT')),
                ('act', models.CharField(db_comment='动作标识', default='save_payroll_edit', max_length=50, verbose_name='动作标识')),
                ('external_id', models.BigIntegerField(db_comment='工单ID', default=0, verbose_name='工单ID')),
                ('external_payroll_result', models.CharField(db_comment='工单状态', default='待处置', max_length=50, verbose_name='工单状态')),
                ('external_roll_number', models.CharField(blank=True, db_comment='工单编号', max_length=100, null=True, verbose_name='工单编号')),
                ('external_product_ids', models.CharField(blank=True, choices=[('', ''), ('申请复核', '申请复核'), ('通过', '通过'), ('不通过', '不通过')], db_comment='三级复核', max_length=50, null=True, verbose_name='三级复核')),
                ('external_addr2', models.CharField(blank=True, choices=[('', ''), ('申请复核', '申请复核'), ('通过', '通过'), ('不通过', '不通过')], db_comment='区县复核', max_length=50, null=True, verbose_name='区县复核')),
                ('external_company_address', models.CharField(blank=True, choices=[('', ''), ('复核通过', '复核通过'), ('超职责范围', '超职责范围')], db_comment='满意研判', max_length=50, null=True, verbose_name='满意研判')),
                ('external_order_number', models.CharField(blank=True, choices=[('', ''), ('复核通过', '复核通过'), ('超职责范围', '超职责范围')], db_comment='解决研判', max_length=50, null=True, verbose_name='解决研判')),
                ('external_normal_payroll_title', models.TextField(blank=True, db_comment='复核原因', null=True, verbose_name='复核原因')),
            ],
            options={
                'verbose_name': '工单表编辑记录',
                'verbose_name_plural': '工单表编辑记录',
                'db_table': 'work_order_base_edit_record',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='base',
            name='external_id',
            field=models.BigIntegerField(db_comment='工单ID', default=0, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='mobile',
            field=models.CharField(db_comment='手机号', default='', max_length=15, validators=[utils.utils.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='title',
            field=models.CharField(db_comment='标题', default='', max_length=100),
        ),
    ]
