# Generated by Django 5.2.1 on 2025-08-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_baseeditrecord_base_external_id_alter_demo_mobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalApiLog',
        ),
        migrations.DeleteModel(
            name='ExternalAuthCaptchaLog',
        ),
        migrations.DeleteModel(
            name='ExternalAuthSession',
        ),
    ]
