# Generated by Django 5.2.1 on 2025-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_alter_base_external_handle_rel_expire_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseeditrecord',
            name='api_endpoint',
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='external_note16',
            field=models.CharField(blank=True, choices=[('', ''), ('是', '是'), ('否', '否')], db_comment='自主研判', max_length=50, null=True, verbose_name='自主研判'),
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='external_note17',
            field=models.TextField(blank=True, db_comment='研判原因', null=True, verbose_name='研判原因'),
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='sync_status',
            field=models.BooleanField(db_comment='同步状态', default=False, verbose_name='同步状态'),
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='sync_task_id',
            field=models.CharField(blank=True, db_comment='同步任务ID', max_length=36, null=True, verbose_name='同步任务ID'),
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='sync_time',
            field=models.DateTimeField(blank=True, db_comment='同步时间', null=True, verbose_name='同步时间'),
        ),
        migrations.AddIndex(
            model_name='baseeditrecord',
            index=models.Index(fields=['external_id'], name='work_order__externa_3f49df_idx'),
        ),
    ]
