# Generated by Django 5.2.1 on 2025-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_remove_baseeditrecord_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='source_system',
            field=models.CharField(db_comment='来源标识', max_length=36, verbose_name='来源标识'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='source_system',
            field=models.CharField(db_comment='来源标识', max_length=36, verbose_name='来源标识'),
        ),
    ]
