# Generated by Django 5.2.1 on 2025-09-12 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_loginlog_location'),
        ('work_order', '0005_alter_base_source_system_alter_meta_source_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='current_node',
            field=models.CharField(blank=True, db_comment='当前节点', max_length=100, null=True, verbose_name='当前节点'),
        ),
        migrations.AddField(
            model_name='base',
            name='department',
            field=models.ManyToManyField(blank=True, db_comment='所属部门', related_name='base_work_orders', to='system.dept', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='base',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.AddField(
            model_name='base',
            name='work_flow',
            field=models.JSONField(blank=True, db_comment='工单流程', default=list, null=True, verbose_name='工单流程'),
        ),
        migrations.AddField(
            model_name='meta',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('name', models.CharField(db_comment='分类名称', max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, db_comment='分类描述', null=True, verbose_name='分类描述')),
                ('parent', models.ForeignKey(blank=True, db_comment='父分类', null=True, on_delete=django.db.models.deletion.CASCADE, to='work_order.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '工单分类',
                'verbose_name_plural': '工单分类',
                'db_table': 'work_order_category',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='base',
            name='category',
            field=models.ManyToManyField(blank=True, db_comment='所属分类', related_name='base_work_orders', to='work_order.category', verbose_name='所属分类'),
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('version', models.CharField(db_comment='版本', max_length=32, verbose_name='版本')),
                ('source_system', models.CharField(db_comment='来源标识', max_length=36, verbose_name='来源标识')),
                ('sync_task_name', models.CharField(blank=True, db_comment='同步任务名称', max_length=100, null=True, verbose_name='同步任务名称')),
                ('sync_task_id', models.CharField(db_comment='同步任务ID', max_length=36, verbose_name='同步任务ID')),
                ('sync_status', models.BooleanField(db_comment='同步状态', default=False, verbose_name='同步状态')),
                ('sync_time', models.DateTimeField(blank=True, db_comment='同步时间', null=True, verbose_name='同步时间')),
                ('external_ps_caption', models.CharField(db_comment='ps_caption', default='处置', max_length=100, verbose_name='ps_caption')),
                ('external_record_number', models.CharField(db_comment='工单编号', max_length=100, verbose_name='工单编号')),
                ('external_public_record', models.IntegerField(db_comment='public_record', default=2, verbose_name='public_record')),
                ('external_user_id_hide', models.CharField(blank=True, db_comment='user_id_hide', max_length=100, null=True, verbose_name='user_id_hide')),
                ('external_co_di_ids', models.CharField(blank=True, db_comment='co_di_ids', max_length=100, null=True, verbose_name='co_di_ids')),
                ('external_co_di_ids_hide', models.CharField(blank=True, db_comment='co_di_ids_hide', max_length=100, null=True, verbose_name='co_di_ids_hide')),
                ('external_pss_status_attr', models.CharField(db_comment='pss_status_attr', default='待处置', max_length=100, verbose_name='pss_status_attr')),
                ('external_di_ids', models.CharField(blank=True, db_comment='di_ids', max_length=100, null=True, verbose_name='di_ids')),
                ('external_di_ids_hide', models.CharField(blank=True, db_comment='di_ids_hide', max_length=100, null=True, verbose_name='di_ids_hide')),
                ('external_psot_name', models.CharField(db_comment='psot_name', default='处置', max_length=100, verbose_name='psot_name')),
                ('external_psot_attr', models.CharField(db_comment='psot_attr', default='处置', max_length=100, verbose_name='psot_attr')),
                ('external_pso_caption', models.CharField(db_comment='pso_caption', default='确定', max_length=100, verbose_name='pso_caption')),
                ('external_note1', models.CharField(blank=True, db_comment='诉求属实', max_length=100, null=True, verbose_name='诉求属实')),
                ('external_distribute_way', models.CharField(blank=True, db_comment='超职责诉求', max_length=100, null=True, verbose_name='超职责诉求')),
                ('external_note8', models.CharField(blank=True, db_comment='申请类型', max_length=100, null=True, verbose_name='申请类型')),
                ('external_d_attachments', models.JSONField(blank=True, db_comment='附件', default=list, null=True, verbose_name='附件')),
                ('external_note3', models.CharField(blank=True, db_comment='联系群众', max_length=100, null=True, verbose_name='联系群众')),
                ('external_note4', models.CharField(blank=True, db_comment='联系号码', max_length=100, null=True, verbose_name='联系号码')),
                ('external_note5', models.CharField(blank=True, db_comment='联系时间', max_length=100, null=True, verbose_name='联系时间')),
                ('external_note6', models.CharField(blank=True, db_comment='是否解决', max_length=100, null=True, verbose_name='是否解决')),
                ('external_note11', models.CharField(blank=True, db_comment='未解决原因', max_length=100, null=True, verbose_name='未解决原因')),
                ('external_note', models.CharField(blank=True, db_comment='办理情况', max_length=100, null=True, verbose_name='办理情况')),
                ('external_note10', models.CharField(blank=True, db_comment='公开答复内容', max_length=100, null=True, verbose_name='公开答复内容')),
                ('attachments_credentials', models.JSONField(blank=True, db_comment='证件附件', default=list, null=True, verbose_name='证件附件')),
                ('attachments_contact', models.JSONField(blank=True, db_comment='联系证据', default=list, null=True, verbose_name='联系证据')),
                ('attachments_handle', models.JSONField(blank=True, db_comment='办理附件', default=list, null=True, verbose_name='办理附件')),
                ('base', models.ForeignKey(db_comment='工单', on_delete=django.db.models.deletion.CASCADE, to='work_order.base', verbose_name='工单')),
            ],
            options={
                'verbose_name': '处置工单',
                'verbose_name_plural': '处置工单',
                'db_table': 'work_order_disposal',
                'ordering': ['-update_time'],
            },
        ),
    ]
