# Generated by Django 5.2.1 on 2025-09-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_loginlog_location'),
        ('work_order', '0006_base_current_node_base_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposal',
            name='external_di_ids',
            field=models.JSONField(blank=True, db_comment='单位名称', default=list, null=True, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='external_di_ids_hide',
            field=models.JSONField(blank=True, db_comment='单位ID', default=list, null=True, verbose_name='单位ID'),
        ),
        migrations.CreateModel(
            name='Distribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('external_ps_caption', models.CharField(db_comment='ps_caption', default='处置', max_length=100, verbose_name='ps_caption')),
                ('external_record_number', models.CharField(db_comment='工单编号', max_length=100, verbose_name='工单编号')),
                ('external_public_record', models.IntegerField(db_comment='public_record', default=2, verbose_name='public_record')),
                ('external_user_id_hide', models.CharField(blank=True, db_comment='user_id_hide', max_length=100, null=True, verbose_name='user_id_hide')),
                ('external_co_di_ids', models.JSONField(blank=True, db_comment='co_di_ids', default=list, null=True, verbose_name='co_di_ids')),
                ('external_co_di_ids_hide', models.JSONField(blank=True, db_comment='co_di_ids_hide', default=list, null=True, verbose_name='co_di_ids_hide')),
                ('external_pss_status_attr', models.CharField(db_comment='pss_status_attr', default='待处置', max_length=100, verbose_name='pss_status_attr')),
                ('external_di_ids', models.JSONField(blank=True, db_comment='单位名称', default=list, null=True, verbose_name='单位名称')),
                ('external_di_ids_hide', models.JSONField(blank=True, db_comment='单位ID', default=list, null=True, verbose_name='单位ID')),
                ('external_psot_name', models.CharField(db_comment='psot_name', default='加派', max_length=100, verbose_name='psot_name')),
                ('external_psot_attr', models.CharField(db_comment='psot_attr', default='加派', max_length=100, verbose_name='psot_attr')),
                ('external_pso_caption', models.CharField(db_comment='pso_caption', default='确定', max_length=100, verbose_name='pso_caption')),
                ('external_dept_send_msg', models.CharField(blank=True, db_comment='单位ID(发短信)', max_length=100, null=True, verbose_name='单位ID')),
                ('external_note', models.CharField(blank=True, db_comment='办理情况', max_length=100, null=True, verbose_name='办理情况')),
                ('external_expires', models.IntegerField(db_comment='办理期限', default=5, verbose_name='办理期限')),
                ('base', models.ForeignKey(db_comment='工单', on_delete=django.db.models.deletion.CASCADE, to='work_order.base', verbose_name='工单')),
            ],
            options={
                'verbose_name': '下派工单',
                'verbose_name_plural': '下派工单',
                'db_table': 'work_order_distribute',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('external_ps_caption', models.CharField(db_comment='ps_caption', default='处置', max_length=100, verbose_name='ps_caption')),
                ('external_record_number', models.CharField(db_comment='工单编号', max_length=100, verbose_name='工单编号')),
                ('external_public_record', models.IntegerField(db_comment='public_record', default=2, verbose_name='public_record')),
                ('external_user_id_hide', models.CharField(blank=True, db_comment='user_id_hide', max_length=100, null=True, verbose_name='user_id_hide')),
                ('external_co_di_ids', models.JSONField(blank=True, db_comment='co_di_ids', default=list, null=True, verbose_name='co_di_ids')),
                ('external_co_di_ids_hide', models.JSONField(blank=True, db_comment='co_di_ids_hide', default=list, null=True, verbose_name='co_di_ids_hide')),
                ('external_pss_status_attr', models.CharField(db_comment='pss_status_attr', default='待处置', max_length=100, verbose_name='pss_status_attr')),
                ('external_di_ids', models.JSONField(blank=True, db_comment='单位名称', default=list, null=True, verbose_name='单位名称')),
                ('external_di_ids_hide', models.JSONField(blank=True, db_comment='单位ID', default=list, null=True, verbose_name='单位ID')),
                ('external_psot_name', models.CharField(db_comment='psot_name', default='督办', max_length=100, verbose_name='psot_name')),
                ('external_psot_attr', models.CharField(db_comment='psot_attr', default='督办', max_length=100, verbose_name='psot_attr')),
                ('external_pso_caption', models.CharField(db_comment='pso_caption', default='确定', max_length=100, verbose_name='pso_caption')),
                ('external_note', models.CharField(blank=True, db_comment='督办意见', max_length=100, null=True, verbose_name='督办意见')),
                ('external_refuse_di_ids', models.JSONField(blank=True, db_comment='督办单位名称', default=list, null=True, verbose_name='督办单位名称')),
                ('external_refuse_di_ids_hide', models.JSONField(blank=True, db_comment='督办单位ID', default=list, null=True, verbose_name='督办单位ID')),
                ('base', models.ForeignKey(db_comment='工单', on_delete=django.db.models.deletion.CASCADE, to='work_order.base', verbose_name='工单')),
            ],
            options={
                'verbose_name': '督办工单',
                'verbose_name_plural': '督办工单',
                'db_table': 'work_order_supervise',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='DistributeOpinionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, db_comment='备注', help_text='备注', max_length=256, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, db_comment='创建人', help_text='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, db_comment='修改人', help_text='修改人', max_length=64, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(db_comment='是否软删除', default=False, verbose_name='是否软删除')),
                ('description', models.TextField(blank=True, db_comment='下派意见预设', null=True, verbose_name='下派意见预设')),
                ('title', models.CharField(blank=True, db_comment='标题', max_length=100, null=True, verbose_name='标题')),
                ('category', models.ForeignKey(db_comment='分类', on_delete=django.db.models.deletion.CASCADE, to='work_order.category', verbose_name='分类')),
                ('dept', models.ForeignKey(db_comment='部门', on_delete=django.db.models.deletion.CASCADE, to='system.dept', verbose_name='部门')),
            ],
            options={
                'verbose_name': '下派意见预设',
                'verbose_name_plural': '下派意见预设',
                'db_table': 'work_order_distribute_opinion_preset',
                'ordering': ['-update_time'],
                'indexes': [models.Index(fields=['dept', 'category'], name='dept_category_idx')],
            },
        ),
    ]
