# Generated by Django 5.2.1 on 2025-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_alter_disposal_external_di_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='sync_response',
            field=models.JSONField(blank=True, db_comment='同步响应', default=dict, null=True, verbose_name='同步响应'),
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='sync_response',
            field=models.JSONField(blank=True, db_comment='同步响应', default=dict, null=True, verbose_name='同步响应'),
        ),
        migrations.AddField(
            model_name='baseeditrecord',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='external_id',
            field=models.BigIntegerField(db_comment='工单ID', default=0, verbose_name='工单ID'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='sync_response',
            field=models.JSONField(blank=True, db_comment='同步响应', default=dict, null=True, verbose_name='同步响应'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='external_id',
            field=models.BigIntegerField(db_comment='工单ID', default=0, verbose_name='工单ID'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='source_system',
            field=models.CharField(blank=True, db_comment='来源标识', default=None, max_length=36, null=True, verbose_name='来源标识'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='sync_response',
            field=models.JSONField(blank=True, db_comment='同步响应', default=dict, null=True, verbose_name='同步响应'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='sync_status',
            field=models.BooleanField(db_comment='同步状态', default=False, verbose_name='同步状态'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='sync_task_id',
            field=models.CharField(blank=True, db_comment='同步任务ID', default=None, max_length=36, null=True, verbose_name='同步任务ID'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', default=None, max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='sync_time',
            field=models.DateTimeField(blank=True, db_comment='同步时间', null=True, verbose_name='同步时间'),
        ),
        migrations.AddField(
            model_name='distribute',
            name='version',
            field=models.CharField(blank=True, db_comment='版本', default=None, max_length=32, null=True, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='meta',
            name='sync_response',
            field=models.JSONField(blank=True, db_comment='同步响应', default=dict, null=True, verbose_name='同步响应'),
        ),
        migrations.AlterField(
            model_name='base',
            name='source_system',
            field=models.CharField(blank=True, db_comment='来源标识', default=None, max_length=36, null=True, verbose_name='来源标识'),
        ),
        migrations.AlterField(
            model_name='base',
            name='sync_task_id',
            field=models.CharField(blank=True, db_comment='同步任务ID', default=None, max_length=36, null=True, verbose_name='同步任务ID'),
        ),
        migrations.AlterField(
            model_name='base',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', default=None, max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.AlterField(
            model_name='base',
            name='version',
            field=models.CharField(blank=True, db_comment='版本', default=None, max_length=32, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='source_system',
            field=models.CharField(blank=True, db_comment='来源标识', default=None, max_length=36, null=True, verbose_name='来源标识'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='sync_task_id',
            field=models.CharField(blank=True, db_comment='同步任务ID', default=None, max_length=36, null=True, verbose_name='同步任务ID'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', default=None, max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='version',
            field=models.CharField(blank=True, db_comment='版本', default=None, max_length=32, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='source_system',
            field=models.CharField(blank=True, db_comment='来源标识', default=None, max_length=36, null=True, verbose_name='来源标识'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='sync_task_id',
            field=models.CharField(blank=True, db_comment='同步任务ID', default=None, max_length=36, null=True, verbose_name='同步任务ID'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='sync_task_name',
            field=models.CharField(blank=True, db_comment='同步任务名称', default=None, max_length=100, null=True, verbose_name='同步任务名称'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='version',
            field=models.CharField(blank=True, db_comment='版本', default=None, max_length=32, null=True, verbose_name='版本'),
        ),
    ]
