# Generated by Django 5.2.1 on 2025-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0008_base_sync_response_baseeditrecord_sync_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='order_number',
            field=models.CharField(blank=True, db_comment='工单编号', max_length=100, null=True, verbose_name='工单编号'),
        ),
        migrations.AddField(
            model_name='meta',
            name='order_step_chart',
            field=models.JSONField(blank=True, db_comment='工单节点流程', default=list, null=True, verbose_name='工单节点流程'),
        ),
        migrations.AddField(
            model_name='meta',
            name='ps_caption_current',
            field=models.CharField(blank=True, db_comment='当前节点', max_length=100, null=True, verbose_name='当前节点'),
        ),
    ]
